simplify code
about illegal-patch
===================

i tried to re-install arch-linux on pure fat fs:

# mkfs -t vfat /dev/sdaX
# mount /dev/sdaX /mnt
# pacstrap /mnt base
---------------------------- 8< ----------------------- 8< -------------------
==> Creating install root at /mnt
==> Installing packages to /mnt
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
:: There are 51 members in group base:
:: Repository core
   1) bash  2) bzip2  3) coreutils  4) cronie  5) cryptsetup  6) device-mapper  7) dhcpcd  8) diffutils  9) e2fsprogs  10) file  11) filesystem  12) findutils  13) gawk  14) gcc-libs  15) gettext  16) glibc  17) grep  18) gzip  19) heirloom-mailx  20) inetutils  21) iproute2  22) iputils  23) jfsutils  24) less  25) licenses  26) linux  27) logrotate  28) lvm2  29) man-db  30) man-pages  31) mdadm  32) nano  33) netctl  34) pacman  35) pciutils  36) pcmciautils  37) perl  38) procps-ng  39) psmisc  40) reiserfsprogs  41) sed  42) shadow  43) sysfsutils  44) systemd-sysvcompat  45) tar  46) texinfo  47) usbutils  48) util-linux  49) vi  50) which  51) xfsprogs

Enter a selection (default=all): 
resolving dependencies...
looking for inter-conflicts...

Targets (111): acl-2.2.52-1  archlinux-keyring-20130525-2  attr-2.4.47-1  ca-certificates-20130610-1  cracklib-2.8.22-3  curl-7.30.0-1  db-5.3.21-1  dbus-1.6.12-1  dirmngr-1.1.1-1  expat-2.1.0-2  gdbm-1.10-1  glib2-2.36.3-2  gmp-5.1.2-1  gnupg-2.0.20-2  gpgme-1.4.1-1  groff-1.22.2-3  hwids-20130607-1  iana-etc-2.30-3  iptables-1.4.19.1-1  kbd-1.15.5-4  keyutils-1.5.5-5  kmod-13-2  krb5-1.11.3-1  libarchive-3.1.2-1  libassuan-2.1.0-1  libcap-2.22-5  libffi-3.0.13-3  libgcrypt-1.5.2-1  libgpg-error-1.11-1  libgssglue-0.4-1  libksba-1.3.0-1  libldap-2.4.35-4  libpipeline-1.2.4-1  libsasl-2.1.26-4  libssh2-1.4.3-1  libtirpc-0.2.3-1  libusbx-1.0.15-1  linux-api-headers-3.8.4-1  linux-firmware-20130610-1  lzo2-2.06-1  mkinitcpio-0.14.0-1  mkinitcpio-busybox-1.20.2-1  mpfr-3.1.2-1  ncurses-5.9-5  openresolv-3.5.5-1  openssl-1.0.1.e-3  pacman-mirrorlist-20130601-1  pam-1.1.6-4  pambase-20130113-1  pcre-8.33-1  pinentry-0.8.3-1  popt-1.16-6  pth-2.0.7-4  readline-6.2.004-1  run-parts-4.3.4-1  systemd-204-3  sysvinit-tools-2.88-11  tzdata-2013c-1  xz-5.0.4-1  zlib-1.2.8-1  bash-4.2.045-4  bzip2-1.0.6-4  coreutils-8.21-2  cronie-1.4.9-4  cryptsetup-1.6.1-2  device-mapper-2.02.98-4  dhcpcd-5.6.8-3  diffutils-3.3-1  e2fsprogs-1.42.8-1  file-5.14-1  filesystem-2013.05-2  findutils-4.4.2-5  gawk-4.1.0-1  gcc-libs-4.8.1-1  gettext-0.18.2.1-1  glibc-2.17-6  grep-2.14-2  gzip-1.6-1  heirloom-mailx-12.5-3  inetutils-1.9.1-6  iproute2-3.9.0-2  iputils-20121221-2  jfsutils-1.1.15-4  less-458-1  licenses-20130203-1  linux-3.9.7-1  logrotate-3.8.5-1  lvm2-2.02.98-4  man-db-2.6.3-3  man-pages-3.51-1  mdadm-3.2.6-4  nano-2.2.6-2  netctl-1.1-1  pacman-4.1.2-1  pciutils-3.2.0-3  pcmciautils-018-7  perl-5.18.0-1  procps-ng-3.3.8-1  psmisc-22.20-1  reiserfsprogs-3.6.22-2  sed-4.2.2-3  shadow-4.1.5.1-6  sysfsutils-2.1.0-8  systemd-sysvcompat-204-3  tar-1.26-4  texinfo-5.1-1  usbutils-007-1  util-linux-2.23.1-2  vi-1:050325-3  which-2.20-6  xfsprogs-3.1.11-1

Total Download Size:    132.07 MiB
Total Installed Size:   428.29 MiB

Proceed with installation? [Y/n] 
:: Retrieving packages from core...
downloading linux-api-headers-3.8.4-1-x86_64.pkg.tar.xz...
downloading tzdata-2013c-1-any.pkg.tar.xz...
downloading iana-etc-2.30-3-any.pkg.tar.xz...
downloading filesystem-2013.05-2-x86_64.pkg.tar.xz...
downloading glibc-2.17-6-x86_64.pkg.tar.xz...
downloading ncurses-5.9-5-x86_64.pkg.tar.xz...
downloading readline-6.2.004-1-x86_64.pkg.tar.xz...
downloading bash-4.2.045-4-x86_64.pkg.tar.xz...
downloading bzip2-1.0.6-4-x86_64.pkg.tar.xz...
downloading gcc-libs-4.8.1-1-x86_64.pkg.tar.xz...
downloading db-5.3.21-1-x86_64.pkg.tar.xz...
downloading zlib-1.2.8-1-x86_64.pkg.tar.xz...
downloading cracklib-2.8.22-3-x86_64.pkg.tar.xz...
downloading libgssglue-0.4-1-x86_64.pkg.tar.xz...
downloading libtirpc-0.2.3-1-x86_64.pkg.tar.xz...
downloading pambase-20130113-1-any.pkg.tar.xz...
downloading pam-1.1.6-4-x86_64.pkg.tar.xz...
downloading attr-2.4.47-1-x86_64.pkg.tar.xz...
downloading acl-2.2.52-1-x86_64.pkg.tar.xz...
downloading gmp-5.1.2-1-x86_64.pkg.tar.xz...
downloading libcap-2.22-5-x86_64.pkg.tar.xz...
downloading coreutils-8.21-2-x86_64.pkg.tar.xz...
downloading run-parts-4.3.4-1-x86_64.pkg.tar.xz...
downloading cronie-1.4.9-4-x86_64.pkg.tar.xz...
downloading libgpg-error-1.11-1-x86_64.pkg.tar.xz...
downloading libgcrypt-1.5.2-1-x86_64.pkg.tar.xz...
downloading shadow-4.1.5.1-6-x86_64.pkg.tar.xz...
downloading util-linux-2.23.1-2-x86_64.pkg.tar.xz...
downloading expat-2.1.0-2-x86_64.pkg.tar.xz...
downloading dbus-1.6.12-1-x86_64.pkg.tar.xz...
downloading pcre-8.33-1-x86_64.pkg.tar.xz...
downloading libffi-3.0.13-3-x86_64.pkg.tar.xz...
downloading glib2-2.36.3-2-x86_64.pkg.tar.xz...
downloading kbd-1.15.5-4-x86_64.pkg.tar.xz...
downloading kmod-13-2-x86_64.pkg.tar.xz...
downloading hwids-20130607-1-any.pkg.tar.xz...
downloading xz-5.0.4-1-x86_64.pkg.tar.xz...
downloading systemd-204-3-x86_64.pkg.tar.xz...
downloading device-mapper-2.02.98-4-x86_64.pkg.tar.xz...
downloading popt-1.16-6-x86_64.pkg.tar.xz...
downloading cryptsetup-1.6.1-2-x86_64.pkg.tar.xz...
downloading dhcpcd-5.6.8-3-x86_64.pkg.tar.xz...
downloading diffutils-3.3-1-x86_64.pkg.tar.xz...
downloading e2fsprogs-1.42.8-1-x86_64.pkg.tar.xz...
downloading file-5.14-1-x86_64.pkg.tar.xz...
downloading findutils-4.4.2-5-x86_64.pkg.tar.xz...
downloading mpfr-3.1.2-1-x86_64.pkg.tar.xz...
downloading gawk-4.1.0-1-x86_64.pkg.tar.xz...
downloading gettext-0.18.2.1-1-x86_64.pkg.tar.xz...
downloading grep-2.14-2-x86_64.pkg.tar.xz...
downloading less-458-1-x86_64.pkg.tar.xz...
downloading gzip-1.6-1-x86_64.pkg.tar.xz...
downloading gdbm-1.10-1-x86_64.pkg.tar.xz...
downloading perl-5.18.0-1-x86_64.pkg.tar.xz...
downloading openssl-1.0.1.e-3-x86_64.pkg.tar.xz...
downloading libsasl-2.1.26-4-x86_64.pkg.tar.xz...
downloading libldap-2.4.35-4-x86_64.pkg.tar.xz...
downloading keyutils-1.5.5-5-x86_64.pkg.tar.xz...
downloading krb5-1.11.3-1-x86_64.pkg.tar.xz...
downloading heirloom-mailx-12.5-3-x86_64.pkg.tar.xz...
downloading inetutils-1.9.1-6-x86_64.pkg.tar.xz...
downloading iptables-1.4.19.1-1-x86_64.pkg.tar.xz...
downloading iproute2-3.9.0-2-x86_64.pkg.tar.xz...
downloading sysfsutils-2.1.0-8-x86_64.pkg.tar.xz...
downloading iputils-20121221-2-x86_64.pkg.tar.xz...
downloading jfsutils-1.1.15-4-x86_64.pkg.tar.xz...
downloading licenses-20130203-1-any.pkg.tar.xz...
downloading linux-firmware-20130610-1-any.pkg.tar.xz...
downloading mkinitcpio-busybox-1.20.2-1-x86_64.pkg.tar.xz...
downloading lzo2-2.06-1-x86_64.pkg.tar.xz...
downloading libarchive-3.1.2-1-x86_64.pkg.tar.xz...
downloading mkinitcpio-0.14.0-1-any.pkg.tar.xz...
downloading linux-3.9.7-1-x86_64.pkg.tar.xz...
downloading logrotate-3.8.5-1-x86_64.pkg.tar.xz...
downloading lvm2-2.02.98-4-x86_64.pkg.tar.xz...
downloading groff-1.22.2-3-x86_64.pkg.tar.xz...
downloading libpipeline-1.2.4-1-x86_64.pkg.tar.xz...
downloading man-db-2.6.3-3-x86_64.pkg.tar.xz...
downloading man-pages-3.51-1-any.pkg.tar.xz...
downloading mdadm-3.2.6-4-x86_64.pkg.tar.xz...
downloading nano-2.2.6-2-x86_64.pkg.tar.xz...
downloading openresolv-3.5.5-1-any.pkg.tar.xz...
downloading netctl-1.1-1-any.pkg.tar.xz...
downloading sed-4.2.2-3-x86_64.pkg.tar.xz...
downloading ca-certificates-20130610-1-any.pkg.tar.xz...
downloading libssh2-1.4.3-1-x86_64.pkg.tar.xz...
downloading curl-7.30.0-1-x86_64.pkg.tar.xz...
downloading pth-2.0.7-4-x86_64.pkg.tar.xz...
downloading libksba-1.3.0-1-x86_64.pkg.tar.xz...
downloading libassuan-2.1.0-1-x86_64.pkg.tar.xz...
downloading pinentry-0.8.3-1-x86_64.pkg.tar.xz...
downloading dirmngr-1.1.1-1-x86_64.pkg.tar.xz...
downloading gnupg-2.0.20-2-x86_64.pkg.tar.xz...
downloading gpgme-1.4.1-1-x86_64.pkg.tar.xz...
downloading pacman-mirrorlist-20130601-1-any.pkg.tar.xz...
downloading archlinux-keyring-20130525-2-any.pkg.tar.xz...
downloading pacman-4.1.2-1-x86_64.pkg.tar.xz...
downloading pciutils-3.2.0-3-x86_64.pkg.tar.xz...
downloading pcmciautils-018-7-x86_64.pkg.tar.xz...
downloading procps-ng-3.3.8-1-x86_64.pkg.tar.xz...
downloading psmisc-22.20-1-x86_64.pkg.tar.xz...
downloading reiserfsprogs-3.6.22-2-x86_64.pkg.tar.xz...
downloading sysvinit-tools-2.88-11-x86_64.pkg.tar.xz...
downloading systemd-sysvcompat-204-3-x86_64.pkg.tar.xz...
downloading tar-1.26-4-x86_64.pkg.tar.xz...
downloading texinfo-5.1-1-x86_64.pkg.tar.xz...
downloading libusbx-1.0.15-1-x86_64.pkg.tar.xz...
downloading usbutils-007-1-x86_64.pkg.tar.xz...
warning: failed to retrieve some files from core
downloading which-2.20-6-x86_64.pkg.tar.xz...
downloading xfsprogs-3.1.11-1-x86_64.pkg.tar.xz...
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
=> ERROR: Failed to install packages to new root
---------------------------- 8< ----------------------- 8< -------------------

# arch-chroot /mnt
---------------------------- 8< ----------------------- 8< -------------------
mount: mount point /mnt/etc/resolv.conf does not exist
chroot: failed to run command /bin/sh: not such file or directory
---------------------------- 8< ----------------------- 8< -------------------

# cat </usr/bin/arch-chroot
---------------------------- 8< ----------------------- 8< -------------------
#!/bin/bash

shopt -s extglob

out() { printf "$1 $2\n" "${@:3}"; }
error() { out "==> ERROR:" "$@"; } >&2
msg() { out "==>" "$@"; }
msg2() { out "  ->" "$@";}
die() { error "$@"; exit 1; }

in_array() {
  local i
  for i in "${@:2}"; do
    [[ $1 = "$i" ]] && return
  done
}

track_mount() {
  mount "$@" && CHROOT_ACTIVE_MOUNTS=("$2" "${CHROOT_ACTIVE_MOUNTS[@]}")
}

api_fs_mount() {
  CHROOT_ACTIVE_MOUNTS=()
  { mountpoint -q "$1" || track_mount "$1" "$1" --bind; } &&
  track_mount proc "$1/proc" -t proc -o nosuid,noexec,nodev &&
  track_mount sys "$1/sys" -t sysfs -o nosuid,noexec,nodev &&
  track_mount udev "$1/dev" -t devtmpfs -o mode=0755,nosuid &&
  track_mount devpts "$1/dev/pts" -t devpts -o mode=0620,gid=5,nosuid,noexec &&
  track_mount shm "$1/dev/shm" -t tmpfs -o mode=1777,nosuid,nodev &&
  track_mount run "$1/run" -t tmpfs -o nosuid,nodev,mode=0755 &&
  track_mount tmp "$1/tmp" -t tmpfs -o mode=1777,strictatime,nodev,nosuid
}

api_fs_umount() {
  umount "${CHROOT_ACTIVE_MOUNTS[@]}"
}

valid_number_of_base() {
  local base=$1 len=${#2} i=

  for (( i = 0; i < len; i++ )); do
    (( (${2:i:1} & ~(base - 1)) == 0 )) || return
  done
}

mangle() {
  local i= chr= out=

  unset {a..f} {A..F}

  for (( i = 0; i < ${#1}; i++ )); do
    chr=${1:i:1}
    case $chr in
      [[:space:]\\])
        printf -v chr '%03o' "'$chr"
        out+=\\
        ;;&
        # fallthrough
      *)
        out+=$chr
        ;;
    esac
  done

  printf '%s' "$out"
}

unmangle() {
  local i= chr= out= len=$(( ${#1} - 4 ))

  unset {a..f} {A..F}

  for (( i = 0; i < len; i++ )); do
    chr=${1:i:1}
    case $chr in
      \\)
        if valid_number_of_base 8 "${1:i+1:3}" ||
            valid_number_of_base 16 "${1:i+1:3}"; then
          printf -v chr '%b' "${1:i:4}"
          (( i += 3 ))
        fi
        ;;&
        # fallthrough
      *)
        out+=$chr
    esac
  done

  printf '%s' "$out${1:i}"
}

dm_name_for_devnode() {
  read dm_name <"/sys/class/block/${1#/dev/}/dm/name"
  if [[ $dm_name ]]; then
    printf '/dev/mapper/%s' "$dm_name"
  else
    # don't leave the caller hanging, just print the original name
    # along with the failure.
    print '%s' "$1"
    error 'Failed to resolve device mapper name for: %s' "$1"
  fi
}

fstype_is_pseudofs() {
  # list taken from util-linux source: libmount/src/utils.c
  local -A pseudofs_types=([anon_inodefs]=1
                           [autofs]=1
                           [bdev]=1
                           [binfmt_misc]=1
                           [cgroup]=1
                           [configfs]=1
                           [cpuset]=1
                           [debugfs]=1
                           [devfs]=1
                           [devpts]=1
                           [devtmpfs]=1
                           [dlmfs]=1
                           [fuse.gvfs-fuse-daemon]=1
                           [fusectl]=1
                           [hugetlbfs]=1
                           [mqueue]=1
                           [nfsd]=1
                           [none]=1
                           [pipefs]=1
                           [proc]=1
                           [pstore]=1
                           [ramfs]=1
                           [rootfs]=1
                           [rpc_pipefs]=1
                           [securityfs]=1
                           [sockfs]=1
                           [spufs]=1
                           [sysfs]=1
                           [tmpfs]=1)
  (( pseudofs_types["$1"] ))
}



usage() {
  cat <<EOF
usage: ${0##*/} chroot-dir [command]

    -h             Print this help message

If 'command' is unspecified, ${0##*/} will launch /bin/sh.

EOF
}

if [[ -z $1 || $1 = @(-h|--help) ]]; then
  usage
  exit $(( $# ? 0 : 1 ))
fi

(( EUID == 0 )) || die 'This script must be run with root privileges'
chrootdir=$1
shift

[[ -d $chrootdir ]] || die "Can't create chroot on non-directory %s" "$chrootdir"

trap '{ api_fs_umount "$chrootdir"; umount "$chrootdir/etc/resolv.conf"; } 2>/dev/null' EXIT

api_fs_mount "$chrootdir" || die "failed to setup API filesystems in chroot %s" "$chrootdir"
track_mount /etc/resolv.conf "$chrootdir/etc/resolv.conf" --bind

SHELL=/bin/sh chroot "$chrootdir" "$@"
---------------------------- 8< ----------------------- 8< -------------------